services:
  postgres:
    container_name: postgres-rtm-dev
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ruest_team_manager
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - rtm-net-dev
  keycloak:
    container_name: keycloak-rtm-dev
    image: quay.io/keycloak/keycloak:26.2.1
    command:
      - start-dev
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: "9090"
      KC_HOSTNAME_STRICT: "false"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - postgres
    networks:
      - rtm-net-dev
volumes:
  postgres_data:
  keycloak_data:
networks:
  rtm-net-dev:
    driver: bridge
