name: Build and Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  backend:
    name: Backend - Maven verify (tests)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
          cache: maven

      - name: Maven verify (unit tests)
        working-directory: ruest-team-manager-be
        run: mvn -B -DskipTests=false verify